version: "3.7"

services:
  vault:
    image: vault:latest
    cap_add:
    - "IPC_LOCK"
    ports:
    - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "TEST"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_TOKEN: "TEST"
      MYSQL_URL: "vault:vault@tcp(mysql:3306)/"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "vault"
      MYSQL_PASSWORD: "vault"

  elastic:
    image: elasticsearch:7.6.0
    ports:
    - "9200:9200"
    environment:
      "discovery.type": "single-node"
      "xpack.security.enabled": "true"
      "ELASTIC_PASSWORD": "elastic"
  ad:
    image: laslabs/alpine-samba-dc:latest
    command: samba
    privileged: true
    ports:
    - "389:389"
    volumes:
    - ${PWD}/testdata/user.ldif:/etc/ad/user.ldif
    environment:
      SAMBA_DC_REALM: "corp.example.net"
      SAMBA_DC_DOMAIN: "EXAMPLE"
      SAMBA_DC_ADMIN_PASSWD: "SuperSecretPassw0rd"
      SAMBA_DC_DNS_BACKEND: "SAMBA_INTERNAL"
      LDAPTLS_REQCERT: "never"
